### ISSUE TITLE
JWEST not maintened anymore

### ISSUE THREAD

**Issue by AMontagu** [ByteInternet/drf-oidc-auth#39]
Hello !

Look like https://github.com/IdentityPython/pyjwkest is not maintened since 12/05/2020.

Today our docker image crash with the error:

```
ImportError: Could not import 'oidc_auth.authentication.JSONWebTokenAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ModuleNotFoundError: No module named 'jwkest'.
```

**Comment by AMontagu** [comment]
Adding pyjwkest manually in the pipfile fixed the problem of the crash. But it doesn't explain why it was working fine until now

**Comment by Amoki** [comment]
I just had the same problem (with poetry)

**Comment by Amoki** [comment]
Maybe just a fresh `pipenv install` from the latest version fixes the issue. Our docker containers try to do a `pipenv install --deploy` with the latest version from an outdated pipenv.lock

**Comment by AMontagu** [comment]
Yeah it make more sense that the problem come from pipenv that from a librairie that was working fine.
Manually added the package to our depency may have updated the pipenv.
