### ISSUE TITLE
[UNMAINTAINED] pyjwkest -> Move to authlib instead?

### ISSUE THREAD

**Issue by Cellebyte** [ByteInternet/drf-oidc-auth#40]
Hey i want to inform that pyjwkest gets unmaintained. Since 30days.

Is it feasable to move to authlib instead?
https://docs.authlib.org/

**Comment by Cellebyte** [comment]
Never mind. Was already mentioned

**Comment by Cellebyte** [comment]
#39 also mentions this.

**Comment by kerrermanisNL** [comment]
Yeah we should probably move away if jwkest is unmaintained. Please note that we're quite swamped with other work, so if you feel like opening a PR it would be much appreciated :)

**Comment by Cellebyte** [comment]
@kerrermanisNL I am also swamped with work, I will see when I have time for this :)
Only want to track it here :)

**Comment by kerrermanisNL** [comment]
Haha, yeah totally understandable :) My closest possibilty will be in about two weeks again. So I'll definitely have a look if I can fix it then

**Comment by kerrermanisNL** [comment]
Haha, looks like I haven't looked at this yet. Going to take a quick peek today

**Comment by Cellebyte** [comment]
I found out, that some things are also missing in authlib.

**Comment by kerrermanisNL** [comment]
Fixed in #42
