### ISSUE TITLE
Django 4.0 Support - ugettext removed from django.utils.translation import 

### ISSUE THREAD

**Issue by hi5grant** [ByteInternet/drf-oidc-auth#63]
It looks like version 2.0.0 of this library isn't compatible with Django 4.0. I just upgraded from 3.0.4 to 4.0.4 and I go the below stack when trying to start the server:

```
File "/Users/.../Library/Python/3.8/lib/python/site-packages/oidc_auth/authentication.py", line 13, in <module>
    from django.utils.translation import ugettext as _
```

I'm not all sure what this import supports or how to upgrade it, but it's kind of a dealbreaker for anyone running Django 4.0
https://github.com/ByteInternet/drf-oidc-auth/blob/0a84995ad8a6709bca1b24253d8225260a22ad05/oidc_auth/authentication.py#L13

**Comment by Amoki** [comment]
This issue is fixed by https://github.com/ByteInternet/drf-oidc-auth/pull/61
